### ISSUE TITLE
Fatal error during compilation after updating to 3.12.0 up to 3.27.x

### ISSUE THREAD

**Issue by Naros** [assertj/assertj#3763]
```
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /home/ccranfor/.m2/wrapper/dists/apache-maven-3.9.8-bin/337e6d14/apache-maven-3.9.8
Java version: 21.0.4, vendor: Oracle Corporation, runtime: /opt/java/jdk-21.0.4
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.12.8-200.fc41.x86_64", arch: "amd64", family: "unix"
```

The build uses Java 21 and the pom is set to a bytecode compatibility of JDK 17; however I have tested at a JDK 21 compatibility level and there is no difference.

If we use `assertj` version 3.11.1, there is no issue. Any version 3.12.0 or later, including up to 3.27.3, the `maven-compiler-plugin` fails with the following error during test compile phase:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile (default-testCompile) on project debezium-core: Fatal error compiling: Cannot load from object array because "this.hashes" is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile (default-testCompile) on project debezium-core: Fatal error compiling
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1231)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:208)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
Caused by: org.codehaus.plexus.compiler.CompilerException: Cannot load from object array because "this.hashes" is null
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess (JavaxToolsCompiler.java:179)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile (JavacCompiler.java:214)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1228)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:208)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
Caused by: java.lang.NullPointerException: Cannot load from object array because "this.hashes" is null
    at com.sun.tools.javac.util.UnsharedNameTable.fromValidUtf (UnsharedNameTable.java:97)
    at com.sun.tools.javac.util.UnsharedNameTable.fromChars (UnsharedNameTable.java:84)
    at com.sun.tools.javac.util.Name$Table.fromString (Name.java:272)
    at com.sun.tools.javac.util.Names.fromString (Names.java:447)
    at com.sun.tools.javac.code.ClassFinder.includeClassFile (ClassFinder.java:482)
    at com.sun.tools.javac.code.ClassFinder.fillIn (ClassFinder.java:738)
    at com.sun.tools.javac.code.ClassFinder.scanUserPaths (ClassFinder.java:695)
    at com.sun.tools.javac.code.ClassFinder.fillIn (ClassFinder.java:570)
    at com.sun.tools.javac.code.ClassFinder.complete (ClassFinder.java:311)
    at com.sun.tools.javac.code.Symbol.complete (Symbol.java:683)
    at com.sun.tools.javac.code.ClassFinder.completeOwners (ClassFinder.java:328)
    at com.sun.tools.javac.code.ClassFinder.complete (ClassFinder.java:296)
    at com.sun.tools.javac.code.Symbol.complete (Symbol.java:683)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.complete (Symbol.java:1452)
    at com.sun.tools.javac.code.Symbol.apiComplete (Symbol.java:689)
    at com.sun.tools.javac.jvm.ClassReader$1.getEnclosingType (ClassReader.java:597)
    at com.sun.tools.javac.code.Printer.visitClassType (Printer.java:228)
    at com.sun.tools.javac.code.Printer.visitClassType (Printer.java:52)
    at com.sun.tools.javac.code.Type$ClassType.accept (Type.java:1050)
    at com.sun.tools.javac.code.Printer.visit (Printer.java:136)
    at com.sun.tools.javac.code.Printer.visitTypes (Printer.java:108)
    at com.sun.tools.javac.code.Printer.printMethodArgs (Printer.java:339)
    at com.sun.tools.javac.code.Printer.visitMethodSymbol (Printer.java:381)
    at com.sun.tools.javac.code.Printer.visitMethodSymbol (Printer.java:52)
    at com.sun.tools.javac.code.Symbol$MethodSymbol.accept (Symbol.java:2305)
    at com.sun.tools.javac.code.Printer.visit (Printer.java:147)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument (AbstractDiagnosticFormatter.java:206)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments (AbstractDiagnosticFormatter.java:167)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage (BasicDiagnosticFormatter.java:111)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMeta (BasicDiagnosticFormatter.java:186)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatDiagnostic (BasicDiagnosticFormatter.java:100)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.format (AbstractDiagnosticFormatter.java:123)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.format (AbstractDiagnosticFormatter.java:75)
    at com.sun.tools.javac.util.JCDiagnostic.toString (JCDiagnostic.java:800)
    at com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.toString (ClientCodeWrapper.java:852)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess (JavaxToolsCompiler.java:145)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile (JavacCompiler.java:214)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1228)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:208)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
```

I also tried with JDK 21.0.6, no difference in outcome:
```
Java version: 21.0.6, vendor: Oracle Corporation, runtime: /opt/java/jdk-21.0.6
```

**Comment by scordio** [comment]
Do I understand correctly that the `debezium-core` is the project failing?

Could you please point me to the right repository to try out?

**Comment by Naros** [comment]
Hi @scordio, yes I was specifically testing just the `debezium-core` module using:
```
./mvnw clean install -DskipITs -pl debezium-core -am
```
You can find the repository at https://github.com/debezium/debezium

**Comment by scordio** [comment]
I managed to get a hint when setting the [`forceLegacyJavacApi`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#forceLegacyJavacApi) parameter to `true` for the `maven-compiler-plugin`.

Now the build fails with:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/stefano/Projects/debezium/debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java:[590,46] error: cannot find symbol
  symbol:   method noneMatch((fieldName[...]ium"))
  location: class IteratorAssert<String>
```

You've probably been hit by a [breaking change of 3.12.0](https://assertj.github.io/doc/#assertj-core-3.12.0-breaking-changes).

Changing [this line](https://github.com/debezium/debezium/blob/844d39d93df07e91f74bf4559777a8386f95a3dd/debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java#L590) to:

```java
assertThat(valueJson.fieldNames()).toIterable().noneMatch(fieldName -> fieldName.startsWith("iodebezium"));
```

allows `testCompile` to work properly, even without the `forceLegacyJavacApi` parameter.

I don't fully understand why the build crashes without that flag, but I suppose this is unrelated to AssertJ.

BTW, I see you have `fest-assert` in some modules:

![Image](https://github.com/user-attachments/assets/798ca2e2-5f5d-422c-9df9-c4c639a20e9b)

You might want to migrate everything to AssertJ 😉

Let us know if there is anything else we could help with.

**Comment by Naros** [comment]
Awesome, thanks for the amazing feedback @scordio, I'll apply these changes today and let you know if I face any other issues. If not, I'll close the issue by end of week.

**Comment by Naros** [comment]
@scordio another unique case I found is in SnapshotIsolationIT in the `debezium-connector-postgres` module on line 122, that performs:
```java
assertThat(record1.sourceOffset()).extracting("snapshot").containsExactly("INITIAL");
```
After the upgrade to 3.27.3, it seems since `sourceOffset` returns a `Map<String,?>` that this fails whereas before it did not. Was that an intended regression?

**Comment by scordio** [comment]
@Naros are there some Maven profiles I need to enable to compile and execute that test?

When running `SnapshotIsolationIT` in the IDE, I'm getting errors like:

```
/Users/stefano/Projects/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java:58:46
java: package io.debezium.connector.postgresql.proto does not exist
```

**Comment by Naros** [comment]
Hi @scordio, since that's an integration test you'll need to do three things.

1. From the command line run `./mvnw clean install -DskipITs -DskipTests` to generate all the intermediate files.
2. Then reimport the project in the IDE
3. Lastly run `cd debezium-connector-postgres && ../mvnw docker:run` to start the PostgreSQL container.

From there you should be able to run the integration test from the IDE without any issues.

**Comment by scordio** [comment]
> [@scordio](https://github.com/scordio) another unique case I found is in SnapshotIsolationIT in the `debezium-connector-postgres` module on line 122, that performs:
> 
> assertThat(record1.sourceOffset()).extracting("snapshot").containsExactly("INITIAL");
> 
> After the upgrade to 3.27.3, it seems since `sourceOffset` returns a `Map<String,?>` that this fails whereas before it did not. Was that an intended regression?

This is another breaking change, this time from [3.13.0](https://assertj.github.io/doc/#assertj-core-3.13.0-breaking-changes).

Wherever you have:

```java
.extracting("...").containsExactly(...);
```

that should become:

```java
.extracting("...").isEqualTo(...);
```

**Comment by scordio** [comment]
@Naros anything else we can help you with?

**Comment by Naros** [comment]
Hi @scordio, I don't think so.  I'll close, and thank you for the help.

**Comment by cstamas** [comment]
Just FYI, this seems Maven m-compiler-p bug: https://github.com/cstamas/javacbug

To circumvent it, use https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#fork

Edit: this was the only thing I found on Google but since then on Maven project the bug is confirmed, so just for the record, if anyone else arrives here via Google.
