### ISSUE TITLE
`describedAs()` erases generic type for `AbstractCollectionAssert`

### ISSUE THREAD

**Issue by shekibobo** [assertj/assertj#2439]
#### Summary

After upgrading from 3.20.2 -> 3.21.0, `describedAs` no longer works correctly with `Set`. It instead requires both the actual and expected sets to first be converted to lists. This happens on any `contains*` type methods or any method that would take an argument of the generic type.

#### Example

```kotlin
        assertThat(setOf<String>("this"))
            .containsExactly("this") // method expects a vararg of type `String`

        assertThat(setOf<String>("this"))
            .describedAs("A set")
            .containsExactly("this") // method expects a vararg of type `Nothing!`


        assertThat(setOf<String>("this").toList())
            .describedAs("A set")
            .containsExactly("this") // method expects a vararg of type `String`
```

## References

* [KT-53113](https://youtrack.jetbrains.com/issue/KT-53113)

**Comment by scordio** [comment]
Thanks, @shekibobo! We'll look into it.

**Comment by scordio** [comment]
@shekibobo could you describe a bit more what exactly is not working?

I tried to reproduce the issue using Java 9 `Set.of()` instead of `setOf` from your example, but all the assertions work correctly without any compile error.

**Comment by temp-droid** [comment]
Hi @scordio , I had a look at it. It seems @shekibobo is using Kotlin and not Java.

![image](https://user-images.githubusercontent.com/82510451/148831774-66fbba87-f83d-49ec-b839-c1f5fbc3959b.png)

And the method used to assert on `setOf` is different from the one used for `.toList()`:

`setOf`:

![image](https://user-images.githubusercontent.com/82510451/148832161-d02f20b4-5269-4a7e-b380-cff0379c7ff5.png)

`toList()`:

![image](https://user-images.githubusercontent.com/82510451/148832224-10d33642-3c47-4838-8b88-838a8a53682d.png)

**Comment by temp-droid** [comment]
The definition of `setOf` is the following:
```kotlin
public fun <T> setOf(element: T): Set<T> = java.util.Collections.singleton(element)
```

And the `Set<T>` type comes from `kotlin.collections`.

The compilation error comes and goes between version `1.7.0` and `3.6.0`.

Starting from version `org.assertj:assertj-core:3.6.0` until `org.assertj:assertj-core:3.20.2`, all tests compile (I didn't try all versions in between).

At that point, the second `setOf` uses the following `assertThat` signature:
```java
public static <ELEMENT> org.assertj.core.api.IterableAssert<ELEMENT> assertThat(     Iterable<? extends ELEMENT> actual )
```

and the third `setOf` uses:
```java
public static <ELEMENT> org.assertj.core.api.ListAssert<ELEMENT> assertThat(     java.util.List<? extends ELEMENT> actual )
```

Version `org.assertj:assertj-core:3.21.0` fails to compile test number 2.   
Since I couldn't find no version `2.20.2`, I suppose there is a typo in the issue description about the major version.  
Issue also reproducible with latest version (`org.assertj:assertj-core:3.22.0`).

Signature is:
```java
public static <E> org.assertj.core.api.AbstractCollectionAssert<?, java.util.Collection<? extends E>, E, org.assertj.core.api.ObjectAssert<E>> assertThat(     java.util.Collection<? extends E> actual )
```

**Comment by scordio** [comment]
Thank for the analysis, @temp-droid. This is most likely caused by 3db7c4ea4e0e2861795dfc8ea599fd6624b66d4f, added in 3.21.0.

**Comment by ajeihala** [comment]
This is related not only to `describedAs` but also ``as`` and `overridingErrorMessage`.
It first started in `v3.21.0`.

Kotlin Example:
```
val a = HashSet<String>()
val b = HashSet<String>()
assertThat(a).doesNotContainAnyElementsOf(b)
```
-> compiles as expected.

But add a line in between:
```
val a = HashSet<String>()
val b = HashSet<String>()
assertThat(a)
    .overridingErrorMessage("test")
    .doesNotContainAnyElementsOf(b)
```
-> compilation error at `(b)`

<img width="526" alt="Screenshot 2022-05-04 at 17 52 20" src="https://user-images.githubusercontent.com/3758340/166721454-7ed7251f-215a-403e-b39a-39c81773daef.png">

**Comment by scordio** [comment]
The cause is indeed 3db7c4ea4e0e2861795dfc8ea599fd6624b66d4f, which added a new `assertThat(Collection)`:

https://github.com/assertj/assertj-core/blob/ea24d9adbb63d8cd16479a4612d2fa5333f5daa6/src/main/java/org/assertj/core/api/Assertions.java#L3227

This triggers compatibility issues with Kotlin, while the same doesn't happen with `assertThat(Iterable)`.

This is probably due to the abstract assertion type returned by the former, since the latter returns a concrete assertion type.

As with the next major version [we plan to stick to abstract types only](https://github.com/assertj/assertj-core/discussions/2229), mainly for third-party libraries, providing a concrete type with `assertThat(Collection)` is not an option.

The next steps could be:
* Investigating if the removal of wildcard type parameters from `assertThat(Collection)` and related classes can fix the issue with Kotlin --> might trigger cascade refactoring with `assertThat(List)` and could break use cases that are not yet tested.
* Adding new Kotlin-specific entry points, e.g., `KotlinAssertions`, that would always return concrete types.

### Workarounds

```kotlin
assertThat(setOf<String>("this") as Iterable<String>)
  .describedAs("A set")
  .containsExactly("this") // method expects a vararg of type `String`
```

```kotlin
CollectionAssert(setOf<String>("this"))
  .describedAs("A set")
  .containsExactly("this") // method expects a vararg of type `String`
```

**Comment by scordio** [comment]
Related: [KT-53113](https://youtrack.jetbrains.com/issue/KT-53113)

**Comment by spyro2000** [comment]
2025 now, still the same problem, still only workarounds available. Will this ever be fixed...?

**Comment by scordio** [comment]
Yes, as it's our chance for delivering breaking changes and becoming better Kotlin citizens 😉

**Comment by scordio** [comment]
[This seems to have been fixed](https://youtrack.jetbrains.com/issue/KT-53113/AssertJ-3.23-tests-dont-compile-with-describedAs-anyMatch#focus=Comments-27-12420146.0-0) in Kotlin 2.2.0.

As we now have Kotlin integration tests, we should add a corresponding test case to verify it.

**Comment by scordio** [comment]
According to #3869 and the related pipeline executions, this issue was already fixed in Kotlin 2.0.

AssertJ never had a clear indication about Kotlin compatibility. For AssertJ 4, we should state that support for Kotlin is guaranteed only for version 2.

**Comment by scordio** [comment]
As previously mentioned, the issue was fixed directly by Kotlin, and corresponding test cases have been added in #3869 to avoid regressions.

In light of this, no further changes are required in AssertJ.
