### ISSUE TITLE
Broken binary compatibility in 3.19.0

### ISSUE THREAD

**Issue by marcphilipp** [assertj/assertj#2190]
#### Summary

Using JUnit Platform's testkit (version 1.7.1) that was compiled against AssertJ 3.16.1 with AssertJ 3.19.0 results in this error:

```
java.lang.NoSuchMethodError: org.assertj.core.api.SoftAssertions.fail(Ljava/lang/String;)V
	at org.junit.platform.testkit.engine.Events.checkCondition(Events.java:455)
	at org.junit.platform.testkit.engine.Events.assertEventsMatchLoosely(Events.java:420)
	at org.junit.platform.testkit.engine.Events.assertEventsMatchLoosely(Events.java:301)
```

Hence it sounds like 3.19.0 broke binary compatibility but not source compatibility. Would you consider adding the method back to restore binary compatibility?

**Comment by scordio** [comment]
Binary compatibility has probably been broken with 820d2927c11e0ddcd371c9de58b40f4245d66fdb.

Adding the method back is not an option as it would have the same signature of https://github.com/assertj/assertj-core/blob/1f0e1f217174deaa6e615d572c158d2e4bca45a2/src/main/java/org/assertj/core/api/AbstractSoftAssertions.java#L58

Either we revert the commit or we keep the breaking change. Anyway, [I made it visible](https://github.com/assertj/doc/commit/4c565d040d2870223a411e9c46506920bbb30929) in the release notes of 3.19.0.

**Comment by joel-costigliola** [comment]
@marcphilipp testkit 1.7.1 is impacted but I guess if the next testkit version is compiled with 3.19.0 then that won't be an issue anymore for 1.7.2+ versions, correct?

I just trying to understand if there is a way forward without reverting this breaking change.

**Comment by sbrannen** [comment]
> @marcphilipp testkit 1.7.1 is impacted but I guess if the next testkit version is compiled with 3.19.0 then that won't be an issue anymore for 1.7.2+ versions, correct?

JUnit Platform 1.8 M2 is already compiling against AssertJ 3.19.0 without any issues. See https://github.com/junit-team/junit5/issues/2603#issuecomment-827586945.

Regarding JUnit Platform 1.7.2+, to the best of my knowledge we haven't discussed upgrading the AssertJ dependency, but if the binary compatibility issue in AssertJ 3.19.0 isn't addressed (for example, in AssertJ 3.19.x) we would then likely need to start depending on AssertJ 3.19.x (instead of 3.16.x) in JUnit Platform 1.7.x and 1.8.x.

**Comment by joel-costigliola** [comment]
Since there is a way forward for JUnit Platform 1.7.2+, we won't revert the changes.
We are happy to help on JUnit Platform 1.7.x and 1.8.x to move to AssertJ 3.19.x.

We are going to try capture these binary incompatibilities in the future release, we are trying `japicmp` for this purpose.

**Comment by sbrannen** [comment]
> Since there is a way forward for JUnit Platform 1.7.2+, we won't revert the changes.

OK. Understood.

> We are happy to help on JUnit Platform 1.7.x and 1.8.x to move to AssertJ 3.19.x.

Thanks for the offer! Though it's really just a change in the version in the build. So I think we'll manage on our own. 😉 
 
> We are going to try capture these binary incompatibilities in the future release, we are trying `japicmp` for this purpose.

Sounds good!

**Comment by joel-costigliola** [comment]
Thanks @sbrannen, I'll close this issue then.
