### ISSUE TITLE
Ambiguous `assertThat` for `Temporal` instance implementing `Comparable`

### ISSUE THREAD

**Issue by armandino** [assertj/assertj#3491]
**Describe the bug**

The upgrade to `3.26.0` results in a compilation error when invoking `assertThat()` with an argument of type `java.time.Year`.

* assertj core version: 3.26.0
* java version: 17

**Test case reproducing the bug**

```java
@Test
void example() {
    Year year = Year.now();
    assertThat(year).isNotNull();
}
```

![image](https://github.com/assertj/assertj/assets/1159054/ab97fec1-4311-4761-ba39-c57eeadcc7b1)

**Comment by scordio** [comment]
Thanks for reporting it, @armandino!

**Comment by Lunatix01** [comment]
We have the same bug 
![image](https://github.com/assertj/assertj/assets/56197620/b5308d72-8c8c-4161-9c1a-8fbf381495fc)

**Comment by scordio** [comment]
In case of `Year` instances, we have a clash between `assertThat(Temporal)` and `assertThat(Comparable)`.

**Comment by scordio** [comment]
Unfortunately, this happens whenever there is an `assertThat` for an interface that extends `Comparable`.

A way forward could be reverting the changes introduced with 46630d71 and introducing `assertThatTemporal` to satisfy @xenoterracide's request at #3404, similar to what we did in 17a52168.
