### PR TITLE
Fix `Instant` and `String` conversion with `Date` assertions

### LINKED ISSUE #3359: Unable to compare some timestamp types
**Describe the bug**

* assertj core version: 3.25.3
* java version: 21.0.1-open
* test framework version: JUnit 5.10.2
* os (if relevant):  Linux 6.5.0-15-generic # 15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 23.10)

**Test case reproducing the bug**

Some timestamp types, for example, `java.sql.Timestamp`, are not specifically handled when comparing with other temporal types, and as a result, though there are no compile-time errors caused by types, they are not effectively compared as temporals.

```java
public class Demo {
    @Test
    void compareSqlTimestampWithInstant() {
        final long now = System.currentTimeMillis();
        final Timestamp ts = new Timestamp(now);
        final Instant instant = Instant.ofEpochMilli(now);
        assertEquals(ts.getNanos(), instant.getNano()); // this succeeds
        assertThat(ts).isEqualTo(instant); // this fails.
        assertThat(ts).isAfterOrEqualTo(instant); // even if I want to relax the check, this still fails
    }
}
```

I can see there are javadocs mentioning that comparisons are done by converting these timestamp types to `java.util.Date`, but is there a way to make this less surprising, otherwise make it a compilation error, so the user can take care of nanoseconds?

**Updated**: I thought it was caused by nano-second precision being dropped along the assertion classes, but it turns out that there is no special handling of such types, and they end up calling `Object.equals()`.

### PR DESCRIPTION
**Pull request by scordio**
This reverts the changes introduced with #3410.

Fixes #3359.

### CODE REVIEW

File: assertj-core/src/main/java/org/assertj/core/api/AbstractDateAssert.java [hunk 1]
```diff
@@ -27,6 +27,7 @@
 import static org.assertj.core.util.Lists.list;
 import static org.assertj.core.util.Lists.newArrayList;
 
+import java.sql.Timestamp;
```
Comment (scordio) [inline assertj-core/src/main/java/org/assertj/core/api/AbstractDateAssert.java:30]: This probably has an underlying impact on the module descriptor as `java.sql` would become required whenever an assertion with an `Instant` parameter is called.

I'll see how we can prove it (related to #2759).

File: assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java [hunk 2]
```diff
@@ -12,42 +12,125 @@
...
+      // THEN
+      then(error).isInstanceOf(AssertionFailedError.class);
+    }
+
+    Arguments[] should_fail() {
+      return new Arguments[] {
+          arguments(Date.from(parse("1970-01-01T00:00:00.000000001Z")),
+                    "1970-01-01T00:00:00.000000001Z"),
+          arguments(Timestamp.from(parse("1970-01-01T00:00:00.000000001Z")),
+                    "1970-01-01T00:00:00.000000001Z")
```
Comment (scordio) [inline assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java:130]: The fact that these cases currently belong to failures might not be 100% correct.

However, I don't see an easy way forward right now so I'd rather document the current behavior with them and we can address this topic in a second step.

Comment (joel-costigliola) [reply assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java:130]: I think we are hitting java `Date` limitation as `SimpleDateFormat` does not handle nanos.
https://stackoverflow.com/questions/30135025/java-date-parsing-with-microsecond-or-nanosecond-accuracy

The best course of action is to document that and point to not to use date assertion accepting string, which was a handy shortcut for users at the time to easily create dates but now with the java.time API it is not necessary and I would even say something we could deprecate.

Comment (scordio) [reply assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java:130]: I wonder if cases like this one and #3382 should be addressed differently, for example dropping the internal usage of `SimpleDateFormat` and favoring `DateTimeFormatter` instead.

For now, I propose to merge these changes as they are, for sure they don't make anything worse, and we can follow up on the `SimpleDateFormat` topic separately.

WDYT?

Comment (joel-costigliola) [reply assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java:130]: Let's merge this and use `DateTimeFormatter` as it handles nanoseconds

File: assertj-core/src/main/java/org/assertj/core/api/AbstractDateAssert.java (hunk 1 above)
Comment (scordio) [reply assertj-core/src/main/java/org/assertj/core/api/AbstractDateAssert.java:30]: I'm not ready yet with #2759 and #3442, which would help demonstrate whether we have a dependency. I'd go ahead with the merge now and fix it later if something pops up.

File: assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java (hunk 2 above)
Comment (scordio) [reply assertj-core/src/test/java/org/assertj/core/api/date/DateAssert_isEqualTo_Test.java:130]: #3482 raised for tracking.
